-- 코드를 입력하세요
SELECT M.CART_ID
FROM 
(SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = "Milk") AS M,
(SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = "Yogurt") AS Y
WHERE M.CART_ID = Y.CART_ID
ORDER BY M.CART_ID
